exports:
  oauth2ProxyDefaults:
    oauth2Proxy:
      proxyServiceName: oauth2-proxy
      proxyPort: 80
      proxyScheme: "http"
      proxyNamespace: ""
  gatewayDefaults:
    authIngress:
      gatewaySettings:
        # proxy: (injected)
        middlewarePrefixOverride: ""
        routeOAuth2Prefix: true
        # parentRefs must be provided by the consuming chart
        parentRefs: []
        authFwdFilter:
          # group and kind must be set to the vendor-specific ExtensionRef target
          # (defaults to Traefik)
          extensionRef:
            group: traefik.io/v1alpha1
            kind: Middleware
        authHeaderFilter:
          enabled: true
          # Actual HTTP response header names and values
          headers:
            Strict-Transport-Security: "max-age=315360000; includeSubDomains; preload"
            X-Content-Type-Options: "nosniff"
            X-Frame-Options: "DENY"
            X-XSS-Protection: "1; mode=block"
  traefikDefaults:
    authIngress:
      traefikSettings:
        # proxy: (injected)
        middlewarePrefixOverride: ""
        routeOAuth2Prefix: true
        authFwdMiddleware:
          create: true
          extraSettings: {}
        errorMiddleware:
          enabled: true
          create: true
          name: ""
          namespace: ""
          settings:
            status:
              - "401"
            query: "/oauth2/sign_in?rd={url}"
            # 'service' defaults to the oauth2 proxy
        authHeaderMiddleware:
          enabled: true
          create: true
          name: ""
          namespace: ""
          headers:
            stsSeconds: 315360000
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsIncludeSubdomains: true
            stsPreload: true
            frameDeny: true
